{
 "title": "Kubernetes Resource Requests",
 "description": "Dashboard to show the resource requests vs allocatable in the cluster",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Cores",
   "type": "graph",
   "description": "This represents the total [CPU resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu) in the cluster.\nFor comparison the total [allocatable CPU cores](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU Cores" }
   ],
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Cluster Total CPU Capacity" },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "Cluster Total Allocatable CPU"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Cluster Total Requested CPU"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[2m])) / sum (machine_cpu_cores)",
     "legendFormat": "Cluster Total CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Cores Requested",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\"}) * 100",
     "legendFormat": "Allocated CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "This represents the total [memory resource requests](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory) in the cluster.\nFor comparison the total [allocatable memory](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node-allocatable.md) is also shown.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Cluster Total Memory Capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "Cluster Total Allocatable Memory"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Cluster Total Requested Memory"
    },
    {
     "expr": "sum(rate(container_memory_usage_bytes[2m])) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Cluster Total Memory Usage"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"}) * 100"
    }
   ]
  }
 ]
}